-- Script para crear la base de datos y todas las tablas en SQL Server basadas en los CSV

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'UDFData')
BEGIN
    CREATE DATABASE UDFData;
END
GO

USE UDFData;
GO

-- Eliminar tablas si existen para evitar errores de duplicidad
DROP TABLE IF EXISTS inspecciones;
DROP TABLE IF EXISTS denuncias;
DROP TABLE IF EXISTS expedientes;
DROP TABLE IF EXISTS eventos;
DROP TABLE IF EXISTS grupo_eventos_codigos;
DROP TABLE IF EXISTS grid_contadores;
DROP TABLE IF EXISTS curva_horaria;
GO

-- Relaciones conceptuales extraídas de las descripciones de los CSV:
-- Contrato, Póliza, Punto de Suministro, Cliente, Equipos de Medida, Consumos, Eventos, Inspecciones, Expedientes y Denuncias están relacionados por identificadores como CUPS, NIS, CNT_ID, etc.
-- Ejemplo: 
-- - Un Expediente está asociado a un Punto de Suministro (CUPS) y a un Cliente.
-- - Un Evento está asociado a un Equipo de Medida (contador) y a un Punto de Suministro.
-- - Una Inspección está asociada a un Cliente y a un Punto de Suministro.
-- - Denuncias y Expedientes pueden estar vinculados por CUPS o NIS.
-- Estas relaciones pueden implementarse como claves foráneas si se dispone de los identificadores exactos en las tablas correspondientes.

-- Tabla: grid_contadores
CREATE TABLE grid_contadores (
    _id BIGINT,
    data_date VARCHAR(50),
    ct_sgc VARCHAR(100),
    ct_gmo VARCHAR(100),
    ct_bdi VARCHAR(100),
    ct_odi VARCHAR(100),
    nombre_ct_bdi VARCHAR(255),
    cnc_s05 VARCHAR(100),
    trafo_bdi INT,
    salida_bt_bdi INT,
    clave_acometida_sgc VARCHAR(100),
    clave_acometida_ficticia_sgc VARCHAR(100),
    nif_sum_sgc VARCHAR(50),
    cups_sgc VARCHAR(50),
    nis_rad_sgc INT,
    nif_pm_sgc VARCHAR(50),
    cgv_pm_sgc VARCHAR(100),
    cnt_sgc VARCHAR(50),
    marca_cnt_sgc VARCHAR(50),
    mod_s06 VARCHAR(50),
    codigo_barras_s06 VARCHAR(50),
    fecha_ult_s06_s06 VARCHAR(50),
    vprime_s06 VARCHAR(50),
    vf_s06 VARCHAR(50),
    version_stg_s05 VARCHAR(50),
    companion_s06 VARCHAR(50),
    ultimo_domingo VARCHAR(50),
    fecha_ult_s05_s05 VARCHAR(50),
    num_dias_uls_s05_s05 INT,
    num_dias_ult_s05_desde_domingo_s05 INT,
    num_dias_ult_s05_o_inst_desde_domingo_s05 INT,
    aea_s05 INT,
    aia_s05 INT,
    num_envios_s05 INT,
    num_envios_s02_s02 INT,
    fecha_ult_s02_s02 VARCHAR(50),
    num_horas_s02_s02 INT,
    num_huecos_s02_s02 INT,
    num_dias_ult_s02_s02 INT,
    num_dias_ult_s02_desde_domingo_s02 INT,
    num_dias_ult_s02_o_inst_desde_domingo_s02 INT,
    fecha_inst_apa_sgc VARCHAR(50),
    num_dias_inst_apa_sgc INT,
    inst_tg_sgc VARCHAR(50),
    telegest_os_sgc VARCHAR(50),
    fr_sgc VARCHAR(50),
    primera_fr_zeus VARCHAR(50),
    aor_fin_pm_sgc VARCHAR(50),
    f_puesta_explotacion_sgc VARCHAR(50),
    tipo_punto_sgc INT,
    tipo_sum_sgc VARCHAR(50),
    estado_contrato_sgc VARCHAR(50),
    fases_sgc VARCHAR(50),
    prop_apa_sgc VARCHAR(50),
    alquiler_distribuidora_zeus VARCHAR(50),
    pot_ctto_sgc INT,
    pot_max_sgc INT,
    tension_sum_sgc VARCHAR(50),
    comercializadora_sgc VARCHAR(100),
    tarifa_sgc VARCHAR(50),
    alquiler_sgc VARCHAR(50),
    fecha_alta_ctto_sgc VARCHAR(50),
    fecha_baja_ctto_sgc VARCHAR(50),
    complemento_fact_sgc VARCHAR(50),
    fecha_ult_lect_sgc VARCHAR(50),
    fecha_ult_fact_sgc VARCHAR(50),
    num_dias_ult_fact_sgc INT,
    contrata_tg_contratas VARCHAR(100),
    contrata_zona_contratas VARCHAR(100),
    area_ejecucion_sgc VARCHAR(100),
    centro_tecnico_sgc VARCHAR(100),
    coord_utm_x_bdi VARCHAR(50),
    coord_utm_y_bdi VARCHAR(50),
    meterid_1_sgc VARCHAR(50),
    meterid_2_sgc VARCHAR(50),
    meterid_3_sgc VARCHAR(50),
    tipo_apa1_sgc VARCHAR(50),
    marca1_sgc VARCHAR(50),
    num_apa1_sgc VARCHAR(50),
    mod1_sgc VARCHAR(50),
    cod_barras1_sgc VARCHAR(50),
    subtipo_apa1_zeus VARCHAR(50),
    tipo_apa2_sgc VARCHAR(50),
    marca2_sgc VARCHAR(50),
    num_apa2_sgc VARCHAR(50),
    mod2_sgc VARCHAR(50),
    cod_barras2_sgc VARCHAR(50),
    subtipo_apa2_zeus VARCHAR(50),
    tipo_apa3_sgc VARCHAR(50),
    marca3_sgc VARCHAR(50),
    num_apa3_sgc VARCHAR(50),
    mod3_sgc VARCHAR(50),
    cod_barras3_sgc VARCHAR(50),
    reactiva_zeus VARCHAR(50),
    maximetro_icp_zeus VARCHAR(50),
    cgv_sum_sgc VARCHAR(100),
    tipo_via_sgc VARCHAR(50),
    calle_sgc VARCHAR(100),
    numero_sgc VARCHAR(20),
    duplicador_sgc VARCHAR(20),
    cod_postal_sgc VARCHAR(20),
    entidad_singular_sgc VARCHAR(100),
    entidad_colectiva_sgc VARCHAR(100),
    municipio_sgc VARCHAR(100),
    provincia_sgc VARCHAR(100),
    ccaa_sgc VARCHAR(100),
    trafos_en_ct INT,
    salidas_bt_en_ct INT,
    salidas_bt_en_trafo INT,
    acometidas_en_ct INT,
    acometidas_en_trafo INT,
    acometidas_por_salida_bt INT,
    contadores_tg_en_ct INT,
    contadores_tg_en_trafo INT,
    contadores_tg_en_salida_bt INT,
    contadores_tg_en_acometida INT,
    tasa_comunica_ct_s05 DECIMAL(16,13),
    tasa_comunica_trafo_s05 DECIMAL(16,13),
    tasa_comunica_salida_bt_s05 DECIMAL(16,13),
    tasa_comunica_acometida_s05 DECIMAL(16,13),
    tasa_5_7_ct_s05 DECIMAL(16,13),
    tasa_5_7_trafo_s05 DECIMAL(16,13),
    tasa_5_7_salida_bt_s05 DECIMAL(16,13),
    tasa_5_7_acometida_s05 DECIMAL(16,13),
    num_trafos_comunica_ko_por_ct INT,
    num_trafos_comunica_parcial_por_ct INT,
    num_trafos_comunica_ok_por_ct INT,
    num_lineas_comunica_ko_por_trafo INT,
    num_lineas_comunica_parcial_por_trafo INT,
    num_lineas_comunica_ok_por_trafo INT,
    num_acometidas_comunica_ko_por_linea INT,
    num_acometidas_comunica_parcial_por_linea INT,
    num_acometidas_comunica_ok_por_linea INT,
    ultimo_s05_distinto_0_odi VARCHAR(50),
    ultimo_s02_distinto_0_odi VARCHAR(50),
    estado_tg_gct VARCHAR(50),
    num_os_ult_inc_sgc VARCHAR(50),
    tipo_os_ult_inc_sgc VARCHAR(50),
    cer_ult_inc_sgc VARCHAR(50),
    fuce_ult_inc_sgc VARCHAR(50),
    num_dias_os_ult_inc_sgc INT,
    accs_ult_inc_sgc VARCHAR(100),
    com_resolucion_ult_inc_zeus VARCHAR(100),
    num_os_ult_sgc VARCHAR(50),
    tipo_os_ult_sgc VARCHAR(50),
    cer_ult_sgc VARCHAR(50),
    fuce_ult_sgc VARCHAR(50),
    num_dias_os_ult_sgc INT,
    accs_ult_sgc VARCHAR(100),
    com_resolucion_ult_zeus VARCHAR(100),
    num_os_ult_acom_zeus VARCHAR(50),
    tipo_os_ult_acom_zeus VARCHAR(50),
    cer_ult_acom_zeus VARCHAR(50),
    fuce_ult_acom_zeus VARCHAR(50),
    num_dias_os_ult_acom_zeus INT,
    accs_ult_acom_zeus VARCHAR(100),
    com_resolucion_ult_acom_zeus VARCHAR(100),
    favoritos_edit VARCHAR(50),
    contrasenyas_edit VARCHAR(50),
    criticidad_edit VARCHAR(50),
    num_incidencia VARCHAR(50),
    estado_incidencia VARCHAR(50),
    fecha_estado_incidencia VARCHAR(50),
    sintoma_incidencia VARCHAR(100),
    reglas_cumplidas VARCHAR(100),
    estado_incidencia_concentrador VARCHAR(50),
    num_dias_ult_cambio_inc_concentrador INT,
    afectado_por_incidencia_cargas VARCHAR(50),
    afectado_por_incidencia_concentrador VARCHAR(50),
    afectado_por_incidencia_ruido VARCHAR(50),
    nivel_ruido VARCHAR(50),
    num_incidencia_ruido VARCHAR(50),
    afectado_por_incidencia_pvpc VARCHAR(50),
    g02_semanal VARCHAR(50),
    t1_modelo_g17 VARCHAR(50),
    t1_version_fw_g17 VARCHAR(50),
    afectado_por_estrategia VARCHAR(50),
    _0_mk_pkms_6b VARCHAR(50),
    _1_lls_pkms_6b VARCHAR(50),
    _2_ak_pkms_6b VARCHAR(50),
    _4_uk_pkms_6b VARCHAR(50),
    _5_factory_lls_pkms_6b VARCHAR(50),
    _6_factory_mk_pkms_6b VARCHAR(50),
    creation_date_mk_pkms_6b VARCHAR(50),
    creation_date_lls_pkms_6b VARCHAR(50),
    creation_date_ak_pkms_6b VARCHAR(50),
    creation_date_uk_pkms_6b VARCHAR(50),
    creation_date_factory_lls_pkms_6b VARCHAR(50),
    creation_date_factory_mk_pkms_6b VARCHAR(50),
    security_status_security VARCHAR(50),
    dc_changed_security VARCHAR(50),
    meter_dc_status_security VARCHAR(50),
    activate_key_status_security VARCHAR(50),
    master_key_status_security VARCHAR(50),
    authenticate_key_status_security VARCHAR(50),
    unicast_key_status_security VARCHAR(50),
    master_activation_key_security VARCHAR(50),
    global_activation_key_security VARCHAR(50),
    fecha_ultimo_s24 VARCHAR(50),
    fecha_ultimo_acceso_s24 VARCHAR(50),
    ultimo_estado_s24 VARCHAR(50),
    active_s24 VARCHAR(50),
    fecha_ultimo_s31 VARCHAR(50),
    s31_estado_cliente_dc VARCHAR(50),
    s31_mascara_de_claves VARCHAR(50),
    s31_cliente_id VARCHAR(50),
    fecha_ultimo_s32 VARCHAR(50),
    origen VARCHAR(50),
    cnae VARCHAR(50),
    tarifa_activa_s23 VARCHAR(50),
    tarifa_latente_s23 VARCHAR(50),
    fecha_activacion_contrato_latente_s23 VARCHAR(50),
    tr1_s23 VARCHAR(50),
    tr2_s23 VARCHAR(50),
    tr3_s23 VARCHAR(50),
    fecha_ultimo_s23_s23 VARCHAR(50),
    ruta VARCHAR(100),
    fecha_ult_s19_s19 VARCHAR(50),
    vf_s19 VARCHAR(50),
    vprime_s19 VARCHAR(50),
    vf_s06_s19 VARCHAR(50),
    vprime_s06_s19 VARCHAR(50),
    fecha_activacion_contrato_activo_s23 VARCHAR(50),
    lote_manual VARCHAR(50),
    lote_telegestionado VARCHAR(50),
    consumo_facturado_ultimo_anyo VARCHAR(50),
    consumo_facturado_el_penultimo_anyo VARCHAR(50),
    ultimo_consumo_facturado VARCHAR(50),
    estado_incidencia_ruido VARCHAR(50),
    filtros_plc_numero_zeus VARCHAR(50),
    filtros_plc_marca_mod_zeus VARCHAR(50),
    filtros_plc_fecha_1__inst_zeus VARCHAR(50),
    filtros_plc_fecha_ult_inst_zeus VARCHAR(50),
    filtros_plc_iguales_zeus VARCHAR(50),
    hora_activacion_contrato_latente_s23 VARCHAR(50),
    hora_activacion_contrato_activo_s23 VARCHAR(50),
    tarifa_empleado VARCHAR(50),
    suministro_no_cortable VARCHAR(10),
    suministro_programable VARCHAR(10),
    pot_contratada_p1 VARCHAR(50),
    max_s04 VARCHAR(50),
    fx_s04 VARCHAR(50),
    fecha_ult_s04_s04 VARCHAR(50),
    fecha_fabricacion_s06 VARCHAR(50),
    ciclos_estimados_zeus INT,
    cnt_gmo VARCHAR(50),
    cnt_online_gmo VARCHAR(50),
    filepath VARCHAR(255),
    data_date_ing BIGINT,
    op VARCHAR(50),
CONSTRAINT PK_grid_contadores_cnt_sgc PRIMARY KEY (cnt_sgc),
CONSTRAINT UQ_grid_contadores_cups_sgc UNIQUE (cups_sgc),
CONSTRAINT UQ_grid_contadores_nis_rad_sgc UNIQUE (nis_rad_sgc)
);

-- Tabla: grupo_eventos_codigos
CREATE TABLE grupo_eventos_codigos (
    Grupo           VARCHAR(50),
    Subgrupo        VARCHAR(50),
    DESCRIPCION     VARCHAR(255),
    Numero          VARCHAR(50),
    DESC_EVENTO     VARCHAR(255),
CONSTRAINT PK_grupo_eventos_codigos PRIMARY KEY (Grupo, Numero)
);

-- Tabla: eventos
CREATE TABLE eventos (
    data_date       DATETIME,
    idrpt           VARCHAR(10),
    idpet           VARCHAR(20),
    version         VARCHAR(20),
    cnc_id          VARCHAR(50),
    cnt_id          VARCHAR(50),
    fh              DATETIME,
    season          VARCHAR(20),
    et              VARCHAR(50),
    c               VARCHAR(50),
    d1              VARCHAR(255),
    d2              VARCHAR(255),
    zip_file        VARCHAR(255),
    xml_file        VARCHAR(255),
    partition_0     VARCHAR(4),
    partition_1     VARCHAR(2),
    partition_2     VARCHAR(2)
);

-- Tabla: denuncias
CREATE TABLE denuncias (
    cups            VARCHAR(50),
    data_date       BIGINT,
    estado          VARCHAR(50),
    fec_alta        VARCHAR(20),
    filepath        VARCHAR(255),
    n__denuncia     VARCHAR(50),
    op              VARCHAR(20)
);

-- Tabla: expedientes
CREATE TABLE expedientes (
    porcentaje_liquidable      FLOAT,
    clasificacion              VARCHAR(100),
    codigo_comercializadora    VARCHAR(50),
    cups                       VARCHAR(50),
    data_date                  BIGINT,
    dg                         INT,
    dias_liquidables           INT,
    energia_facturada          INT,
    energia_liquidable         INT,
    estado                     VARCHAR(50),
    estado_suministro          VARCHAR(50),
    fec_acta                   VARCHAR(20),
    fec_alta                   VARCHAR(20),
    fec_estado                 VARCHAR(20),
    fecha_fin_anomalia         VARCHAR(20),
    fecha_inicio_anomalia      VARCHAR(20),
    fechafinfacturaemitida     VARCHAR(20),
    fechainiciofacturaemitida  VARCHAR(20),
    filepath                   VARCHAR(255),
    irregularidades_detectadas VARCHAR(255),
    metodo_estimacion          VARCHAR(100),
    motivonofacturable         VARCHAR(100),
    n__informe                 VARCHAR(50),
    nis                        INT,
    nombre_comercializadora    VARCHAR(100),
    num_factura_atr            VARCHAR(50),
    num_factura_levantamiento  VARCHAR(50),
    num_ooss                   VARCHAR(50),
    op                         VARCHAR(20),
    tarifa                     VARCHAR(20),
    tipo_anomalia              VARCHAR(50),
    valoracion_total           INT
);

-- Tabla: curva_horaria
CREATE TABLE curva_horaria (
    data_date VARCHAR(50),
    idrpt VARCHAR(50),
    idpet VARCHAR(50),
    version VARCHAR(20),
    cnc_id VARCHAR(100),
    cnt_id VARCHAR(50),
    magn BIGINT,
    fh DATETIME,
    season VARCHAR(20),
    bc VARCHAR(10),
    ai FLOAT,
    ae FLOAT,
    r1 FLOAT,
    r2 FLOAT,
    r3 FLOAT,
    r4 FLOAT,
    zip_file VARCHAR(255),
    xml_file VARCHAR(255),
    aud_tim DATETIME,
    partition_0 VARCHAR(4),
    partition_1 VARCHAR(2),
    partition_2 VARCHAR(2),
    CONSTRAINT PK_curva_horaria PRIMARY KEY (cnt_id, cnc_id, data_date)
);

-- Tabla: inspecciones (solo campos principales por longitud)
CREATE TABLE inspecciones (
    csv_file                VARCHAR(100),
    data_date               DATE,
    nis_rad                 INT,
    estado_ctt              VARCHAR(50),
    fecha_alta_ctto         DATE,
    fecha_alta_sum          DATE,
    fecha_baja_ctto         DATE,
    fecha_baja_ctto_ant     DATE,
    solicitud               VARCHAR(100),
    proceso                 VARCHAR(100),
    nif                     VARCHAR(30),
    tarifa                  VARCHAR(20),
    tip_os                  VARCHAR(20),
    descripcion_os          VARCHAR(100),
    num_os                  VARCHAR(50),
    cer                     VARCHAR(20),
    fecha_generacion        DATE,
    fuce                    DATE,
    acc_1                   VARCHAR(255),
    acc_2                   VARCHAR(255),
    acc_3                   VARCHAR(255),
    acc_4                   VARCHAR(255),
    acc_5                   VARCHAR(255),
    acc_6                   VARCHAR(255),
    acc_7                   VARCHAR(255),
    acc_8                   VARCHAR(255),
    acc_9                   VARCHAR(255),
    acc_10                  VARCHAR(255),
    acc_11                  VARCHAR(255),
    acc_12                  VARCHAR(255),
    acc_13                  VARCHAR(255),
    acc_14                  VARCHAR(255),
    acc_15                  VARCHAR(255),
    precio_os               VARCHAR(20),
    num_apa1                VARCHAR(50),
    marca1                  VARCHAR(50),
    tip_apa_1               VARCHAR(50),
    ten_apa_1               VARCHAR(20),
    f_inst_apa_1            DATE,
    num_apa2                VARCHAR(50),
    marca2                  VARCHAR(50),
    tip_apa_2               VARCHAR(50),
    ten_apa_2               VARCHAR(20),
    f_inst_apa_2            DATE,
    num_apa3                VARCHAR(50),
    marca3                  VARCHAR(50),
    tip_apa_3               VARCHAR(50),
    ten_apa_3               VARCHAR(20),
    f_inst_apa_3            DATE,
    tipo_sum                VARCHAR(50),
    direccion               VARCHAR(255),
    ent_singular            VARCHAR(100),
    ent_colectiva           VARCHAR(100),
    municipio               VARCHAR(100),
    provincia               VARCHAR(100),
    area_ejecucion          VARCHAR(100),
    comentario_generacion   VARCHAR(255),
    descripcion_resolucion  VARCHAR(255),
    icp_instalado           VARCHAR(10),
    f_inst_icp              DATE,
    fases                   VARCHAR(20),
    intensidad_icp          VARCHAR(20),
    cod_resuelve_os         VARCHAR(50),
    cod_contrata            VARCHAR(50),
    contrata                VARCHAR(100),
    usuario_genera_os       VARCHAR(50),
    propiedad_apa           VARCHAR(50),
    nom_propiedad           VARCHAR(50),
    ult_lect                VARCHAR(50),
    fecha_ult_lect          DATE,
    cnae                    INT,
    tipo_punto              INT,
    fecha_primer_envio_contrata DATE,
    alimentacion            VARCHAR(255),
    coord_x                 VARCHAR(50),
    coord_y                 VARCHAR(50),
    per_lect                VARCHAR(20),
    cod_retorno_sat         INT,
    cod_lector              VARCHAR(50),
    nombre_lector           VARCHAR(100),
    cod_operario            VARCHAR(50),
    nombre_operario         VARCHAR(100),
    tip_apa_lvn             VARCHAR(50),
    num_apa_lvn             VARCHAR(50),
    marca_apa_lvn           INT,
    lect_csmo_11            VARCHAR(20),
    lect_csmo_12            VARCHAR(20),
    lect_csmo_14            VARCHAR(20),
    estado_apa_inst_1       VARCHAR(20),
    estado_apa_inst_2       VARCHAR(20),
    estado_apa_inst_3       VARCHAR(20),
    cod_barras              VARCHAR(50),
    modelo                  VARCHAR(50),
    amperios                VARCHAR(20),
    amperios_med1           VARCHAR(20),
    calle                   VARCHAR(100),
    cbarras_med1            VARCHAR(50),
    cgv_pm                  VARCHAR(50),
    clave_acometida         VARCHAR(50),
    cod_comer               VARCHAR(50),
    cod_postal              VARCHAR(10),
    dup                     VARCHAR(50),
    fases_con               VARCHAR(20),
    fases_med1              VARCHAR(20),
    fecha_inst_con          DATE,
    gcv                     VARCHAR(50),
    int_prim_con            VARCHAR(20),
    lect_med11              VARCHAR(20),
    lect_med12              VARCHAR(20),
    lect_med13              VARCHAR(20),
    lect_med14              VARCHAR(20),
    lect_med15              VARCHAR(20),
    lect_med16              VARCHAR(20),
    lect_med17              VARCHAR(20),
    marca_con               VARCHAR(50),
    metid_med1              VARCHAR(50),
    nif_fi_apa              VARCHAR(30),
    nombre_usu              VARCHAR(100),
    nombre_usu_telef        VARCHAR(20),
    nombre_comer            VARCHAR(100),
    num_apa_con             VARCHAR(50),
    numero                  VARCHAR(20),
    pot_ctto                VARCHAR(20),
    pot_max                 VARCHAR(20),
    pot_pag_pr              VARCHAR(20),
    pot_hp6_1               VARCHAR(20),
    pot_hp6_2               VARCHAR(20),
    pot_hp6_3               VARCHAR(20),
    pot_hp6_4               VARCHAR(20),
    pot_hp6_5               VARCHAR(20),
    pot_hp6_6               VARCHAR(20),
    prop_con                VARCHAR(20),
    rel_trans_con           VARCHAR(20),
    tcsmo_med11             VARCHAR(20),
    tcsmo_med12             VARCHAR(20),
    tcsmo_med13             VARCHAR(20),
    tcsmo_med14             VARCHAR(20),
    tcsmo_med15             VARCHAR(20),
    tcsmo_med16             VARCHAR(20),
    tcsmo_med17             VARCHAR(20),
    tens_sum                VARCHAR(20),
    tension_con             VARCHAR(20),
    tip_apa_con             VARCHAR(20),
    tip_local               VARCHAR(20),
    tipo_via                VARCHAR(20),
    estado_os               VARCHAR(20),
    fecha_ini_os            DATE,
    fecha_fin_os            DATE,
    descripcion_acciones_os VARCHAR(255),
    punto_medida            VARCHAR(50),
    motivo                  VARCHAR(100),
    id_action1              VARCHAR(20),
    id_action2              VARCHAR(20),
    id_action3              VARCHAR(20),
    id_action4              VARCHAR(20),
    id_action5              VARCHAR(20),
    id_action6              VARCHAR(20),
    id_action7              VARCHAR(20),
    id_action8              VARCHAR(20),
    id_action9              VARCHAR(20),
    id_action10             VARCHAR(20),
    id_action11             VARCHAR(20),
    id_action12             VARCHAR(20),
    id_action13             VARCHAR(20),
    id_action14             VARCHAR(20),
    id_action15             VARCHAR(20),
    grupo_trabajo           VARCHAR(50),
    prioridad               VARCHAR(20),
    fecha_solicitud_ejecucion DATE,
    fecha_programada        DATE,
    fecha_maxima_ejecucion  DATE,
    fecha_minima_ejecucion  DATE,
    aud_tim                 DATETIME,
    partition_0             VARCHAR(4),
    partition_1             VARCHAR(2),
    partition_2             VARCHAR(2)
);

-- Comentarios extendidos para tablas y columnas (basados en los CSV)
-- Tabla eventos
EXEC sp_addextendedproperty N'MS_Description', N'Eventos o alarmas que emiten los contadores de Telegestión', N'SCHEMA', N'dbo', N'TABLE', N'eventos';
EXEC sp_addextendedproperty N'MS_Description', N'Fecha de carga de la información', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'data_date';
EXEC sp_addextendedproperty N'MS_Description', N'Identificador del repositorio (S09 siempre)', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'idrpt';
EXEC sp_addextendedproperty N'MS_Description', N'Identificador de la petición (0=programada, <>0=no programada)', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'idpet';
EXEC sp_addextendedproperty N'MS_Description', N'Versión del protocolo PRIME', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'version';
EXEC sp_addextendedproperty N'MS_Description', N'ID del concentrador (nodo principal de telegestión)', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'cnc_id';
EXEC sp_addextendedproperty N'MS_Description', N'ID del contador (meter_id del suministro)', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'cnt_id';
EXEC sp_addextendedproperty N'MS_Description', N'Fecha y hora del evento', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'fh';
EXEC sp_addextendedproperty N'MS_Description', N'Estación', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'season';
EXEC sp_addextendedproperty N'MS_Description', N'Grupo Evento', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'et';
EXEC sp_addextendedproperty N'MS_Description', N'Código evento', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'c';
EXEC sp_addextendedproperty N'MS_Description', N'Descripción 1', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'd1';
EXEC sp_addextendedproperty N'MS_Description', N'Descripción 2', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'd2';
EXEC sp_addextendedproperty N'MS_Description', N'Nombre del fichero zip de donde proviene el dato', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'zip_file';
EXEC sp_addextendedproperty N'MS_Description', N'Nombre del fichero xml de donde proviene el dato', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'xml_file';
EXEC sp_addextendedproperty N'MS_Description', N'Año', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'partition_0';
EXEC sp_addextendedproperty N'MS_Description', N'Mes', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'partition_1';
EXEC sp_addextendedproperty N'MS_Description', N'Día', N'SCHEMA', N'dbo', N'TABLE', N'eventos', N'COLUMN', N'partition_2';

-- Tabla denuncias
EXEC sp_addextendedproperty N'MS_Description', N'Tiene información y estado de las denuncias realizadas', N'SCHEMA', N'dbo', N'TABLE', N'denuncias';
EXEC sp_addextendedproperty N'MS_Description', N'CUPS', N'SCHEMA', N'dbo', N'TABLE', N'denuncias', N'COLUMN', N'cups';
EXEC sp_addextendedproperty N'MS_Description', N'Fecha de carga', N'SCHEMA', N'dbo', N'TABLE', N'denuncias', N'COLUMN', N'data_date';
EXEC sp_addextendedproperty N'MS_Description', N'Estado de la denuncia', N'SCHEMA', N'dbo', N'TABLE', N'denuncias', N'COLUMN', N'estado';
EXEC sp_addextendedproperty N'MS_Description', N'Fecha de alta en la base de datos', N'SCHEMA', N'dbo', N'TABLE', N'denuncias', N'COLUMN', N'fec_alta';
EXEC sp_addextendedproperty N'MS_Description', N'Ruta del archivo fuente', N'SCHEMA', N'dbo', N'TABLE', N'denuncias', N'COLUMN', N'filepath';
EXEC sp_addextendedproperty N'MS_Description', N'Número de la denuncia', N'SCHEMA', N'dbo', N'TABLE', N'denuncias', N'COLUMN', N'n__denuncia';
EXEC sp_addextendedproperty N'MS_Description', N'Operación', N'SCHEMA', N'dbo', N'TABLE', N'denuncias', N'COLUMN', N'op';

-- Tabla expedientes
EXEC sp_addextendedproperty N'MS_Description', N'Informes levantados con anomalía efectiva', N'SCHEMA', N'dbo', N'TABLE', N'expedientes';
EXEC sp_addextendedproperty N'MS_Description', N'Porcentaje de liquidable', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'porcentaje_liquidable';
EXEC sp_addextendedproperty N'MS_Description', N'Clasificación de la anomalía', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'clasificacion';
EXEC sp_addextendedproperty N'MS_Description', N'Código de la comercializadora', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'codigo_comercializadora';
EXEC sp_addextendedproperty N'MS_Description', N'CUPS', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'cups';
EXEC sp_addextendedproperty N'MS_Description', N'Fecha de carga', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'data_date';
EXEC sp_addextendedproperty N'MS_Description', N'Número duplicador del expediente', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'dg';
EXEC sp_addextendedproperty N'MS_Description', N'Días liquidables', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'dias_liquidables';
EXEC sp_addextendedproperty N'MS_Description', N'Energía facturada', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'energia_facturada';
EXEC sp_addextendedproperty N'MS_Description', N'Energía liquidable', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'energia_liquidable';
EXEC sp_addextendedproperty N'MS_Description', N'Estado del expediente', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'estado';
EXEC sp_addextendedproperty N'MS_Description', N'Estado del suministro', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'estado_suministro';
EXEC sp_addextendedproperty N'MS_Description', N'Fecha de acta', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'fec_acta';
EXEC sp_addextendedproperty N'MS_Description', N'Fecha de alta del expediente', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'fec_alta';
EXEC sp_addextendedproperty N'MS_Description', N'Fecha del último estado', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'fec_estado';
EXEC sp_addextendedproperty N'MS_Description', N'Fecha final de la anomalía', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'fecha_fin_anomalia';
EXEC sp_addextendedproperty N'MS_Description', N'Fecha de inicio de la anomalía', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'fecha_inicio_anomalia';
EXEC sp_addextendedproperty N'MS_Description', N'Fecha final de la factura emitida', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'fechafinfacturaemitida';
EXEC sp_addextendedproperty N'MS_Description', N'Fecha de inicio de la factura emitida', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'fechainiciofacturaemitida';
EXEC sp_addextendedproperty N'MS_Description', N'Ruta del archivo fuente', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'filepath';
EXEC sp_addextendedproperty N'MS_Description', N'Irregularidades detectadas', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'irregularidades_detectadas';
EXEC sp_addextendedproperty N'MS_Description', N'Método de estimación', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'metodo_estimacion';
EXEC sp_addextendedproperty N'MS_Description', N'Motivo no facturable', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'motivonofacturable';
EXEC sp_addextendedproperty N'MS_Description', N'Número del expediente', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'n__informe';
EXEC sp_addextendedproperty N'MS_Description', N'NIS', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'nis';
EXEC sp_addextendedproperty N'MS_Description', N'Nombre de la comercializadora', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'nombre_comercializadora';
EXEC sp_addextendedproperty N'MS_Description', N'Número de factura emitida', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'num_factura_atr';
EXEC sp_addextendedproperty N'MS_Description', N'Número de factura por levantamiento', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'num_factura_levantamiento';
EXEC sp_addextendedproperty N'MS_Description', N'Número de OOSS', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'num_ooss';
EXEC sp_addextendedproperty N'MS_Description', N'Operación', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'op';
EXEC sp_addextendedproperty N'MS_Description', N'Tarifa', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'tarifa';
EXEC sp_addextendedproperty N'MS_Description', N'Tipo de anomalía', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'tipo_anomalia';
EXEC sp_addextendedproperty N'MS_Description', N'Valoración del expediente', N'SCHEMA', N'dbo', N'TABLE', N'expedientes', N'COLUMN', N'valoracion_total';

-- INSERTS para grupo_eventos_codigos
INSERT INTO grupo_eventos_codigos (Grupo, Subgrupo, DESCRIPCION, Numero, DESC_EVENTO) VALUES
('1, 2, 3, 4, 5 y 6', NULL, 'Reset de evento', '255', 'Indica que el evento ha sido limpiado'),
('1', '10', 'Arranques y Fallos Alimentación', '1', 'Arranque registrador con perdida de datos'),
('1', '10', 'Arranques y Fallos Alimentación', '2', 'Arranque registrador sin perdida de datos'),
('1', '10', 'Arranques y Fallos Alimentación', '3', 'Fallo alimentación registrador (apagado)'),
('1', '10', 'Arranques y Fallos Alimentación', '4', 'Fallo tensión de medida fase 1'),
('1', '10', 'Arranques y Fallos Alimentación', '5', 'Fallo tensión de medida fase 2'),
('1', '10', 'Arranques y Fallos Alimentación', '6', 'Fallo tensión de medida fase 3'),
('1', '10', 'Arranques y Fallos Alimentación', '7', 'Pérdida de neutro'),
('1', '10', 'Arranques y Fallos Alimentación', '8', 'Batería baja'),
('1', '10', 'Errores Internos críticos de fabricante', '9', 'Error interno crítico'),
('1', '10', 'Otros errores fabricante', '10', 'otros errores'),
('1', '10', 'Otros errores fabricante', '21', 'Fin Fallo tensión Fase 1'),
('1', '10', 'Otros errores fabricante', '22', 'Fin Fallo tensión Fase 2'),
('1', '10', 'Otros errores fabricante', '23', 'Fin Fallo tensión Fase 3'),
('1', '10', 'Otros errores fabricante', '24', 'Cambio oficial hora: Invierno --> Verano'),
('1', '10', 'Otros errores fabricante', '25', 'Cambio oficial hora: Verano --> Invierno'),
('1', '10', 'Reserva para usos futuros', '26-29', 'Reservado'),
('1', '10', 'Cambio de Parámetros', '30', 'Cambio parámetros registrador (parámetros no incluidos en otros eventos de cambio de parámetros)'),
('1', '10', 'Cambio de Parámetros', '31', 'Cambio configuración puertos comunicaciones'),
('1', '10', 'Cambio de Parámetros', '32', 'Cambio Clave Consulta/Lectura'),
('1', '10', 'Cambio de Parámetros', '33', 'Cambio Clave Parametrización'),
('1', '10', 'Cambio de Parámetros', '34', 'Cambio Clave Firmware'),
('1', '10', 'Cambio de Parámetros', '35', 'Realizado Reset de Batería'),
('1', '10', 'Cambio de Parámetros', '36', 'Cambio de Cambio Automático I/V'),
('1', '10', 'Cambio de Parámetros', '37', 'Cambio Tiempo Mínimo entre Cierres'),
('1', '10', 'Cambio de Parámetros', '38', 'Cambio Periodo Integración Curvas de Carga'),
('1', '10', 'Cambio de Parámetros', '39', 'Cambio Relación Transformación (solo para MI)'),
('1', '10', 'Cambio de Parámetros', '40', 'Cambio Tipo Sincronismo Reloj'),
('1', '10', 'Cambio de Parámetros', '41', 'Cambio Etiqueta Programación'),
('1', '10', 'Cambio de Parámetros', '42', 'Cambio Estado Activación Cierres por Pulsador'),
('1', '10', 'Cambio de Parámetros', '43', 'Cambio Asignación de Salidas'),
('1', '10', 'Contrato 1', '44', 'Cierre Contrato 1 por comando'),
('1', '10', 'Contrato 1', '45', 'Cambio parámetros Contrato 1'),
('1', '10', 'Contrato 1', '46', 'Reserva uso futuro'),
('1', '10', 'Contrato 1', '47', 'Cambio Tabla Días Especiales Contrato 1 latente'),
('1', '10', 'Contrato 1', '48', 'Cambio Tabla Temporadas Contrato 1 latente'),
('1', '10', 'Contrato 1', '49', 'Borrada Programación Contrato 1 latente'),
('1', '10', 'Contrato 1', '50', 'Cambio Cierres Automáticos Contrato 1 latente'),
('1', '10', 'Contrato 1', '51', 'Cambio Fecha Activación Contrato 1 latente'),
('1', '10', 'Contrato 2', '52', 'Cierre Contrato 2 por comando'),
('1', '10', 'Contrato 2', '53', 'Cambio parámetros Contrato 2'),
('1', '10', 'Contrato 2', '54', 'Cambio Tabla Días Especiales Contrato 2 latente'),
('1', '10', 'Contrato 2', '55', 'Cambio Tabla Temporadas Contrato 2 latente'),
('1', '10', 'Contrato 2', '56', 'Borrada Programación Contrato 2 latente'),
('1', '10', 'Contrato 2', '57', 'Cambio Cierres Automáticos Contrato 2 latente'),
('1', '10', 'Contrato 2', '58', 'Cambio Fecha Activación Contrato 2 latente'),
('1', '10', 'Contrato 3', '59', 'Cierre Contrato 3 por comando'),
('1', '10', 'Contrato 3', '60', 'Cambio parámetros Contrato 3'),
('1', '10', 'Contrato 3', '61', 'Cambio Tabla Días Especiales Contrato 3 latente'),
('1', '10', 'Contrato 3', '62', 'Cambio Tabla Temporadas Contrato 3 latente'),
('1', '10', 'Contrato 3', '63', 'Borrada Programación Contrato 3 latente'),
('1', '10', 'Contrato 3', '64', 'Cambio Cierres Automáticos Contrato 3 latente'),
('1', '10', 'Contrato 3', '65', 'Cambio Fecha Activación Contrato 3 latente'),
('1', '10', 'Contrato 1, 2 y 3', '66', 'Cierre manual (por pulsador)'),
('1', '10', 'Reserva para usos futuros', '67-89', 'Reservado'),
('1', '10', 'cambio de parámetros de calidad de suministro', '90', 'Cambio de tiempo para variación de tensión (T)'),
('1', '10', 'cambio de parámetros de calidad de suministro', '91', 'Cambio de tiempo de interrupción larga (T'')'),
('1', '10', 'cambio de parámetros de calidad de suministro', '92', 'Cambio de Tensión Referencia (V)'),
('1', '10', 'cambio de parámetros de calidad de suministro', '93', 'Cambio de Consigna superior de tensión (+V)'),
('1', '10', 'cambio de parámetros de calidad de suministro', '94', 'Cambio de Consigna inferior de tensión (-V)'),
('1', '10', 'cambio de parámetros de calidad de suministro', '95', 'Cambio del umbral para estado de falta de tensión.'),
('2', '20', 'Control elemento corte', '1', 'Conexión manual (botón)'),
('2', '20', 'Control elemento corte', '2', 'Desconexión remota (comando)'),
('2', '20', 'Control elemento corte', '3', 'Conexión remota (comando)'),
('2', '20', 'Control elemento corte', '4', 'Desconexión por control de potencia contratada Contrato 1'),
('2', '20', 'Control elemento corte', '13', 'Desconexión por control de potencia contratada Contrato 3'),
('2', '20', 'Control elemento corte', '5', 'Conexión control de potencia (IGA)'),
('2', '20', 'Control elemento corte', '6', 'Inicio Bloqueo elemento por superación PSC (valido para importación y exportación)'),
('2', '20', 'Control elemento corte', '7', 'Habilitación del elemento'),
('2', '20', 'Control elemento corte', '8', 'Deshabilitación del elemento'),
('2', '20', 'Control elemento corte', '9', 'Desconexión por control de potencia residual'),
('2', '20', 'Control elemento corte', '10', 'Conexión por desactivación potencia residual'),
('2', '20', 'Control elemento corte', '11', 'Conexión por control de potencia residual '),
('2', '20', 'Control elemento corte', '12', 'Cambio de modo de control del elemento de corte'),
('2', '20', 'Control elemento corte', '14', 'Fin Bloqueo elemento por superación PSC (válido para importación y exportación)'),
('2', '20', 'Reserva para usos futuros', '15-255', NULL),
('3', '31', 'Calidad.', '1', 'VALOR MEDIO de las TENSIONES ENTRE FASES BAJO LIMITE INFERIOR:'),
('3', '31', 'Incidencias ABIERTAS', '2', 'TENSIÓN FASE 1 BAJO LIMITE INFERIOR'),
('3', '31', 'Incidencias ABIERTAS', '3', 'TENSIÓN FASE 2 BAJO LIMITE INFERIOR'),
('3', '31', 'Incidencias ABIERTAS', '4', 'TENSIÓN FASE 3 BAJO LIMITE INFERIOR'),
('3', '31', 'Incidencias ABIERTAS', '5', 'VALOR MEDIO de las TENSIONES ENTRE FASES SOBRE LIMITE SUPERIOR:'),
('3', '31', 'Incidencias ABIERTAS', '6', 'TENSIÓN FASE 1 SOBRE LIMITE SUPERIOR'),
('3', '31', 'Incidencias ABIERTAS', '7', 'TENSIÓN FASE 2 SOBRE LIMITE SUPERIOR'),
('3', '31', 'Incidencias ABIERTAS', '8', 'TENSIÓN FASE 3 SOBRE LIMITE SUPERIOR:'),
('3', '31', 'Incidencias ABIERTAS', '9', 'CORTE DE LARGA DURACIÓN EN TODAS LAS FASES'),
('3', '31', 'Incidencias ABIERTAS', '10', 'CORTE DE LARGA DURACIÓN EN LA FASE1'),
('3', '31', 'Incidencias ABIERTAS', '11', 'CORTE DE LARGA DURACIÓN EN LA FASE2'),
('3', '31', 'Incidencias ABIERTAS', '12', 'CORTE DE LARGA DURACIÓN EN LA FASE3'),
('3', '31', 'Incidencias ABIERTAS', '25', 'FALTA ALTA IMPEDANCIA (Supervisor BT)'),
('3', '32', 'Calidad.', '13', 'VALOR MEDIO de las TENSIONES ENTRE FASES BAJO LIMITE INFERIOR:'),
('3', '32', 'Incidencias CERRADAS', '14', 'TENSIÓN FASE 1 BAJO LIMITE INFERIOR'),
('3', '32', 'Incidencias CERRADAS', '15', 'TENSIÓN FASE 2 BAJO LIMITE INFERIOR'),
('3', '32', 'Incidencias CERRADAS', '16', 'TENSIÓN FASE 3 BAJO LIMITE INFERIOR'),
('3', '32', 'Incidencias CERRADAS', '17', 'VALOR MEDIO de las TENSIONES ENTRE FASES SOBRE LIMITE SUPERIOR:'),
('3', '32', 'Incidencias CERRADAS', '18', 'TENSIÓN FASE 1 SOBRE LIMITE SUPERIOR '),
('3', '32', 'Incidencias CERRADAS', '19', 'TENSIÓN FASE 2 SOBRE LIMITE SUPERIOR'),
('3', '32', 'Incidencias CERRADAS', '20', 'TENSIÓN FASE 3 SOBRE LIMITE SUPERIOR'),
('3', '32', 'Incidencias CERRADAS', '21', 'CORTE DE LARGA DURACIÓN EN TODAS LAS FASES'),
('3', '32', 'Incidencias CERRADAS', '22', 'CORTE DE LARGA DURACIÓN EN LA FASE1'),
('3', '32', 'Incidencias CERRADAS', '23', 'CORTE DE LARGA DURACIÓN EN LA FASE2'),
('3', '32', 'Incidencias CERRADAS', '24', 'CORTE DE LARGA DURACIÓN EN LA FASE3'),
('3', '32', 'Incidencias CERRADAS', '26', 'FIN DE FALTA DE  ALTA IMPEDANCIA (Supervisor BT)'),
('3', '32', 'Reserva para usos futuros', '27-255', NULL),
('4', '40', 'Fraude', '1', 'APERTURA DE LA ENVOLVENTE PRECINTO FABRICANTE'),
('4', '40', 'Fraude', '2', 'CIERRE DE LA ENVOLVENTE PRECINTO FABRICANTE'),
('4', '40', 'Fraude', '3', 'APARICIÓN DE UN CAMPO MAGNÉTICO SUPERIOR A NORMA (NO APLICA)'),
('4', '40', 'Fraude', '4', 'DESAPARICIÓN DE UN CAMPO MAGNÉTICO (NO APLICA)'),
('4', '40', 'Fraude', '5', 'PRESENCIA INTENSIDAD ANTE AUSENCIA DE TENSIÓN'),
('4', '40', 'Fraude', '6', 'INTENTO ACCESO CON CLAVE ERRÓNEA (INTRUSIÓN)'),
('4', '40', 'Fraude', '7', 'APERTURA DE LA TAPA CUBRE BORNAS / CUBRE HILOS'),
('4', '40', 'Fraude', '8', 'CIERRE DE LA TAPA CUBRE BORNAS / CUBRE HILOS'),
('4', '40', 'Fraude', '9', 'INICIO DETECCIÓN TENSIÓN EN BORNES SALIDA ANTE APERTURA E.CORTE POR COMANDO'),
('4', '40', 'Fraude', '10', 'FIN DETECCIÓN TENSIÓN EN BORNES SALIDA ANTE APERTURA E.CORTE POR COMANDO'),
('4', '40', 'Fraude', '11', 'INICIO DETECCIÓN IMPEDANCIA INFINITA EN BORNES SALIDA ANTE APERTURA E.CORTE POR COMANDO'),
('4', '40', 'Fraude', '12', 'FIN DETECCIÓN IMPEDANCIA INFINITA EN BORNES SALIDA ANTE APERTURA E.CORTE POR COMANDO'),
('4', '40', 'Fraude', '13', 'INICIO PUENTEO CONTADOR (OPCIONAL)'),
('4', '40', 'Fraude', '14', 'FIN PUENTEO CONTADOR (OPCIONAL)'),
('4', '40', 'Reserva para usos futuros', '13-255', NULL),
('5', '50', 'Gestión de la demanda', '1', 'Recepción orden gestión de la demanda potencia residual crítica'),
('5', '50', 'Gestión de la demanda', '2', 'Recepción orden gestión de la demanda reducción % potencia crítica'),
('5', '50', 'Gestión de la demanda', '3', 'Recepción orden gestión de la demanda valor absoluto de potencia crítica'),
('5', '50', 'Gestión de la demanda', '4', 'Recepción orden gestión de la demanda potencia residual no critica'),
('5', '50', 'Gestión de la demanda', '5', 'Aceptación gestión de la demanda por cliente potencia residual no critica'),
('5', '50', 'Gestión de la demanda', '6', 'Rechazo gestión de la demanda por cliente potencia residual no critica'),
('5', '50', 'Gestión de la demanda', '7', 'Recepción orden gestión de la demanda reducción % potencia no critica'),
('5', '50', 'Gestión de la demanda', '8', 'Aceptación gestión de la demanda por cliente reducción % potencia no critica'),
('5', '50', 'Gestión de la demanda', '9', 'Rechazo gestión de la demanda por cliente reducción % potencia no critica'),
('5', '50', 'Gestión de la demanda', '10', 'Recepción orden gestión de la demanda potencia valor absoluto no critica'),
('5', '50', 'Gestión de la demanda', '11', 'Aceptación gestión de la demanda por cliente potencia absoluto no critica'),
('5', '50', 'Gestión de la demanda', '12', 'Rechazo gestión de la demanda por cliente potencia absoluto no critica'),
('5', '50', 'Gestión de la demanda', '13', 'Cambio valor programación potencia residual contratada. Valor previo y actual'),
('5', '50', 'Gestión de la demanda', '14', 'Activación/Inicio potencia residual. Valor previo y actual.'),
('5', '50', 'Gestión de la demanda', '15', 'Fin potencia residual'),
('5', '50', 'Gestión de la demanda', '16', 'Activación/Inicio reducción % potencia contratada'),
('5', '50', 'Gestión de la demanda', '17', 'Fin reducción % potencia contratada'),
('5', '50', 'Gestión de la demanda', '18', 'Activación/Inicio reducción potencia absoluta'),
('5', '50', 'Gestión de la demanda', '19', 'Fin reducción potencia absoluta'),
('5', '50', 'Gestión de la demanda', '20', 'Potencia demanda cercana a la potencia contratada (%)'),
('5', '50', 'Reserva para usos futuros', '21-255', NULL),
('6', '60', 'Alta ocurrencia - Comunes', '1', 'Inicio establecimiento de comunicacones puerto PLC'),
('6', '60', 'Alta ocurrencia - Comunes', '2', 'Fin de comunicacones puerto PLC'),
('6', '60', 'Alta ocurrencia - Comunes', '3', 'Inico establecimiento de comunicacones puerto óptico '),
('6', '60', 'Alta ocurrencia - Comunes', '4', 'Fin de comunicacones puerto óptico'),
('6', '60', 'Alta ocurrencia - Comunes', '5', 'Inicio establecimiento de comunicacones puerto serie'),
('6', '60', 'Alta ocurrencia - Comunes', '6', 'Fin de comunicacones puerto serie'),
('6', '60', 'Reserva para usos futuros', '7-255', NULL),
('7', '71', 'Operaciones de seguridad correctas', '1', 'Key Reset'),
('7', '71', 'Operaciones de seguridad correctas', '2', 'Cambio Master key'),
('7', '71', 'Operaciones de seguridad correctas', '3', 'Cambio Global Unicast Encryption Key'),
('7', '71', 'Operaciones de seguridad correctas', '4', 'Cambio Authentication Key'),
('7', '71', 'Operaciones de seguridad correctas', '5', 'Cambio password LLS del cliente seguro PLC'),
('7', '71', 'Operaciones de seguridad correctas', '6', 'Cambio Security policy  (Value = 3)'),
('7', '72', 'Errores en operaciones de seguridad', '7', 'Error cambio Master key'),
('7', '72', 'Errores en operaciones de seguridad', '8', 'Error cambio Global Unicast Encryption Key'),
('7', '72', 'Errores en operaciones de seguridad', '9', 'Error cambio Authentication Key'),
('7', '72', 'Errores en operaciones de seguridad', '10', 'Error en el establecimiento de la asociación con clave dedicada'),
('7', '72', 'Errores en operaciones de seguridad', '11', 'Error en el cifrado y autenticación de los mensajes'),
('7', '72', 'Errores en operaciones de seguridad', '12', 'Error en el password LLS'),
('7', '72', 'Errores en operaciones de seguridad', '13', 'Error en el cambio de Security policy'),
('7', '72', 'Errores en operaciones de seguridad', '14-255', NULL);

-- Claves foráneas (añadidas después de los INSERTS)
ALTER TABLE grid_contadores
ADD CONSTRAINT FK_grid_contadores_curva_horaria FOREIGN KEY (cnt_sgc, cnc_s05, data_date) REFERENCES curva_horaria(cnt_id, cnc_id, data_date);

ALTER TABLE eventos
ADD CONSTRAINT FK_eventos_cnt_id FOREIGN KEY (cnt_id) REFERENCES grid_contadores(cnt_sgc);

ALTER TABLE eventos
ADD CONSTRAINT FK_eventos_grupo_eventos_codigos FOREIGN KEY (et, c) REFERENCES grupo_eventos_codigos(Grupo, Numero);

ALTER TABLE expedientes
ADD CONSTRAINT FK_expedientes_cups FOREIGN KEY (cups) REFERENCES grid_contadores(cups_sgc);

ALTER TABLE expedientes
ADD CONSTRAINT FK_expedientes_nis FOREIGN KEY (nis) REFERENCES grid_contadores(nis_rad_sgc);

ALTER TABLE denuncias
ADD CONSTRAINT FK_denuncias_grid_contadores FOREIGN KEY (cups) REFERENCES grid_contadores(cups_sgc);

-- Aquí puedes añadir las demás claves foráneas según el modelo relacional
